spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.221:3306/edu?characterEncoding=UTF-8
    username: root
    password: mysql123123
    # 数据源其他配置
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall # ,log4j
    # 最大活跃数
    maxActive: 20
    # 初始化数量
    initialSize: 5
    # 最大连接等待超时时间
    maxWait: 60000
    # 打开 PSCache ，并且指定每个连接 PSCache 的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置公用监控数据
    useGlobalDataSourceStat: true
    # 通过设置 connectionProperties 属性来打开 mergeSql 功能；慢 SQL 记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

  # JPA
  jpa:
    show-sql: true

# mybatis 配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bdqn.edu.entity
